request_id = "devops_aws_dev_b0523d65"
department = "DevOps"
created_by = "manoharkadimisetti3@gmail.com"
environment = "dev"
instance_type = "t3.medium"
storage_size = "50GB"
region = "us-east-1"
associate_public_ip = true
ami_filter = "ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*"
ami_owners = ["099720109477"]
key_name = "yes, deploy"
create_new_keypair = true
vpc_id = "vpc-0ad261ab35ff584e6"
use_existing_vpc = true
subnet_id = "subnet-0f610f5e0c62f97cc"
use_existing_subnet = true
security_group_id = "sg-0b05cb2f2d827a52f"
use_existing_sg = true
instance_tags = {
  "Name" = "manohar-ec2-b0523d65"
  "Department" = "DevOps"
  "Environment" = "dev"
  "RequestID" = "devops_aws_dev_b0523d65"
  "CreatedBy" = "manoharkadimisetti3@gmail.com"
  "ManagedBy" = "AIOps-Platform"
}